#!/usr/bin/env bash

usage() {
  echo "usage: `basename \"$0\"` <pdf-file> [<dir>]";
}

if [ "$#" -lt "1" ]; then
  echo "you must provide pdf-file.";
  usage;
  exit 1;
fi

pdf=$1

name=`basename $pdf`

prefix=""
if [ "`echo $name | grep \"^test-\"`" != "" ]; then
  prefix="test-"
fi

if [ ! -e $pdf ]; then
  echo "$pdf does not exist."
  exit 1;
fi

if [ "`file $pdf | grep "PDF document"`" == "" ]; then
  echo "$pdf must be a pdf file"
  exit 1;
fi

dir=$2
if [ "$dir" != "" ] && [ ! -e "$dir" ]; then
  echo "$dir does not exist"
  exit 1;
fi

CWD=`pwd`
TMP=`mktemp -d`

cd $TMP

# split into pages
pdftk $pdf burst

# convert to png
for _pdf in `ls pg_????.pdf`; do
  png=`echo $_pdf | sed "s/pdf/png/"`;
  sips -s format png $_pdf --out $png >/dev/null;
done

if [ "$prefix" != "" ]; then
  for file in `ls pg_*.png`; do
    mv $file "$prefix$file"
  done
fi

# move to dir/
if [ "$dir" != "" ]; then
  mv ./*.png $dir/
else
  mv ./*.png $CWD/ 2>&1>/dev/null
fi

# clean up
rm doc_data.txt
rm pg_*.pdf

cd $CWD
